/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddAi: typeof import('./../src/components/add-ai.vue')['default']
    ChatPage: typeof import('./../src/components/chat-page.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui-taro')['ActionSheet']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
  }
}
